"""Prometheus metrics for the AIAUDITOR engine service.

Exposes the same business + infrastructure metrics as the Go services,
plus reasoning-engine-specific metrics.

Usage::

    from engine.shared.metrics import (
        ENGAGEMENTS_ACTIVE, EVIDENCE_INGESTED, REASONING_DURATION,
        start_metrics_server,
    )
    import time

    ENGAGEMENTS_ACTIVE.set(5)
    EVIDENCE_INGESTED.inc()

    start = time.time()
    # ... do reasoning ...
    REASONING_DURATION.observe(time.time() - start)
"""
from __future__ import annotations

import threading
from wsgiref.simple_server import make_server
from typing import Any

from prometheus_client import (
    Counter,
    Gauge,
    Histogram,
    REGISTRY,
    make_wsgi_app,
    start_http_server,
)
from prometheus_client import CONTENT_TYPE_LATEST, generate_latest

# ── Infrastructure metrics ─────────────────────────────────────────────────────

REQUEST_DURATION = Histogram(
    "request_duration_seconds",
    "Duration of HTTP requests in seconds.",
    labelnames=["service", "method", "path", "status"],
    buckets=(0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1.0, 2.5, 5.0, 7.5, 10.0),
)

REQUEST_TOTAL = Counter(
    "request_total",
    "Total number of HTTP requests processed.",
    labelnames=["service", "method", "path", "status"],
)

ERROR_TOTAL = Counter(
    "error_total",
    "Total number of HTTP error responses (status >= 400).",
    labelnames=["service", "method", "path"],
)

# ── Business metrics ──────────────────────────────────────────────────────────

ENGAGEMENTS_ACTIVE = Gauge(
    "aiauditor_engagements_active",
    "Number of currently active audit engagements.",
)

EVIDENCE_INGESTED = Counter(
    "aiauditor_evidence_items_ingested_total",
    "Total number of evidence items ingested across all engagements.",
)

CONCLUSIONS_GENERATED = Counter(
    "aiauditor_conclusions_generated_total",
    "Total number of audit conclusions generated by the reasoning engine.",
)

QUALITY_GATES_BLOCKED = Counter(
    "aiauditor_quality_gates_blocked_total",
    "Total number of evidence submissions blocked by quality gates.",
)

COVERAGE_RATE = Gauge(
    "aiauditor_coverage_rate",
    "Current evidence coverage rate across all active engagements (0.0\u20131.0).",
)

REASONING_DURATION = Histogram(
    "aiauditor_reasoning_duration_seconds",
    "Duration of reasoning pipeline executions in seconds.",
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
)


def start_metrics_server(port: int = 9090) -> None:
    """Start a Prometheus metrics HTTP server on :port/metrics in a daemon thread."""
    try:
        start_http_server(port)
    except OSError as exc:
        import logging
        logging.getLogger(__name__).warning(
            "Could not start metrics server on :%d: %s", port, exc
        )

