// Package metrics provides Prometheus metrics for AIAUDITOR services.
//
// Infrastructure metrics (per-service, per-endpoint):
//   - request_duration_seconds  histogram
//   - request_total             counter
//   - error_total               counter
//
// Business metrics (platform-wide):
//   - aiauditor_engagements_active                 gauge
//   - aiauditor_evidence_items_ingested_total      counter
//   - aiauditor_conclusions_generated_total        counter
//   - aiauditor_quality_gates_blocked_total        counter
//   - aiauditor_coverage_rate                      gauge
//   - aiauditor_reasoning_duration_seconds         histogram
package metrics

import (
	"net/http"
	"strconv"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// Infrastructure metrics
var (
	// RequestDuration tracks HTTP request latency by service, method, path, and status code.
	RequestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "request_duration_seconds",
			Help:    "Duration of HTTP requests in seconds.",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"service", "method", "path", "status"},
	)

	// RequestTotal counts total HTTP requests.
	RequestTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "request_total",
			Help: "Total number of HTTP requests processed.",
		},
		[]string{"service", "method", "path", "status"},
	)

	// ErrorTotal counts HTTP error responses (status >= 400).
	ErrorTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "error_total",
			Help: "Total number of HTTP error responses (status >= 400).",
		},
		[]string{"service", "method", "path"},
	)
)

// Business metrics
var (
	// EngagementsActive is the current number of active audit engagements.
	EngagementsActive = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "aiauditor_engagements_active",
		Help: "Number of currently active audit engagements.",
	})

	// EvidenceItemsIngestedTotal counts all evidence items ingested.
	EvidenceItemsIngestedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "aiauditor_evidence_items_ingested_total",
		Help: "Total number of evidence items ingested across all engagements.",
	})

	// ConclusionsGeneratedTotal counts all audit conclusions produced by the reasoning engine.
	ConclusionsGeneratedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "aiauditor_conclusions_generated_total",
		Help: "Total number of audit conclusions generated by the reasoning engine.",
	})

	// QualityGatesBlockedTotal counts submissions blocked by quality gates.
	QualityGatesBlockedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "aiauditor_quality_gates_blocked_total",
		Help: "Total number of evidence submissions blocked by quality gates.",
	})

	// CoverageRate is the current evidence coverage rate (0.0–1.0) across active engagements.
	CoverageRate = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "aiauditor_coverage_rate",
		Help: "Current evidence coverage rate across all active engagements (0.0–1.0).",
	})

	// ReasoningDuration tracks reasoning pipeline execution times.
	ReasoningDuration = promauto.NewHistogram(prometheus.HistogramOpts{
		Name:    "aiauditor_reasoning_duration_seconds",
		Help:    "Duration of reasoning pipeline executions in seconds.",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0},
	})
)

// responseWriter wraps http.ResponseWriter to capture the status code.
type responseWriter struct {
	http.ResponseWriter
	statusCode int
	written    bool
}

func (rw *responseWriter) WriteHeader(code int) {
	if !rw.written {
		rw.statusCode = code
		rw.written = true
	}
	rw.ResponseWriter.WriteHeader(code)
}

func (rw *responseWriter) status() int {
	if rw.statusCode == 0 {
		return http.StatusOK
	}
	return rw.statusCode
}

// Middleware returns an http.Handler middleware that records request duration,
// total request count, and error count for the named service.
// It can wrap both Chi and Gin engines (both implement http.Handler).
func Middleware(service string) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			start := time.Now()
			rw := &responseWriter{ResponseWriter: w}

			next.ServeHTTP(rw, r)

			latency := time.Since(start).Seconds()
			code := strconv.Itoa(rw.status())
			path := r.URL.Path
			method := r.Method

			RequestDuration.WithLabelValues(service, method, path, code).Observe(latency)
			RequestTotal.WithLabelValues(service, method, path, code).Add(1)
			if rw.status() >= 400 {
				ErrorTotal.WithLabelValues(service, method, path).Add(1)
			}
		})
	}
}

